#!/bin/bash

if [[ "$#" < 3 ]] ; then
    echo "Please write the name of the directory, the header and the files separated by spaces"
    exit;
fi

ARRAY=("$@")

DIRECTORIO="${ARRAY[0]}"
HEADERMAY="${ARRAY[1]^^}"
HEADERMIN="${ARRAY[1],,}"
FILES="${ARRAY[@]:2}"

/*Create the directory and move to it*/
mkdir $DIRECTORIO && cd $DIRECTORIO && 
/* && means If the previous step fails, do not continue with the script */

/* Print the structure for everyfile in stdoutput */
echo -e "#include \"$HEADERMIN.h\"
/**
 * function_name - function description
 * @a: description of parameter a
 * @b: description of parameter b
 * Return: description of the return of this function
 */
prototype whitout semicolon
{
/* Remember to check first if parameters exists */
return (0);
}" | 

/* Create files, and print the previous on each file */
tee $FILES && 

/* Create the structure of the header file */
echo -e "#ifndef $HEADERMAY \b_H
#define $HEADERMAY \b_H

/* -- Different libraries for c functions --*/
#include <stdio.h> /* For printf */
#include <unistd.h> /* For fork, execve */
#include <stdlib.h> /* For exit failure or success */
#include <string.h> /* For strtok, strlen */
#include <errno.h> /* For errno and perror */
#include <sys/types.h> /* For type pid */
#include <sys/wait.h> /* For wait */
#include <sys/stat.h> /* For use of stat function */
#include <fcntl.h> /* For open files */
#include <ctype.h> /* For isdigit */

int _putchar(char c); /* Delete thsi line if you aren't a holberton student from the first trimester*/

#endif /* $HEADERMAY \b_H */" | 

/* Create the header file and print inside the content */
tee $HEADERMIN.h && 

/* Create the content of the readmefile*/
echo -E "
# Title
General description and objectives.

## Compilation

\`\`\`c
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 main.c file_name.c
\`\`\`\`

## Environment
 This project has been tested on \`Ubuntu 14.06.6 LTS\`


>## Authors

* **Natalia Vera** [github](https://github.com/Naveduran) - naveduran@gmail.com
" | 
/* Print the content ofn the readme file */
tee README.md
