#!/bin/bash

ARRAY="$@"
COMMIT="{$ARRAY[0]}"

for FILE in "${ARRAY[@]:1}"; do
    if [[ $FILE == *.c || $FILE == *.h ]]; then
	if [[ $(betty $FILE 2>&1 > /dev/null) ]]; then
	    betty $FILE
	fi
    fi
done
git add $@
git commit -m "$COMMIT"
git push origin main
