#!/bin/bash

COMMIT="$1"

if [[ $# < 2 ]] ; then
    echo Write dino, the commit between double quotes, and write the file or files to upload.
fi

for FILE in "${@:2}"; do
    if [[ $FILE == *.c || $FILE == *.h ]]; then
	b=$(betty $FILE)
	if [[ $(echo $b | grep -o "ERROR") || $(echo $b | grep -o "WARNING") ]]; then
	    betty $b
	    exit
	fi

    fi
done
git add ${@:2}
git commit -m "$COMMIT"
git push
